### ISSUE TITLE
Mixed -- connect Spotify services to component 

### ISSUE THREAD

**Issue by BitsyBirb** [UNLV-CS472-672/2024-S-GROUP3-Barbell#109]
Design and implement an API to integrate Spotify's API and get the following information from a user:
* Of currently playing track * 
* Name of album + url to album image
* Artist(s) + url
* Song title + url
* Is a song currently playing?
* Amount of time elapsed for song + total length of song

All fields can be null, depends on if a song is currently playing (that field will always return true if a song is playing, false otherwise).

* Note *
* Use this link as reference on what fields to get from .json returned by Spotify. Second link provides rough idea of how to approach API
* https://developer.spotify.com/documentation/web-api/reference/get-the-users-currently-playing-track
* https://medium.com/@alagappan.dev/create-a-now-playing-widget-using-the-spotify-web-api-in-react-a6cb564ed923

**Comment by thienguen** [comment]
fall over to cycle 9 from cycle 6

**Comment by thienguen** [comment]
This has been completed in a joint issue. Closed
