### ISSUE TITLE
Design -- Create a 'search/add friends' function for the friends search

### ISSUE THREAD

**Issue by supakeshi** [UNLV-CS472-672/2024-S-GROUP3-Barbell#139]
create a mock-up for a new feature that will allow a user to search for friends, or if the person is not in their friends list, to give the option to add them as a friend

**Comment by thienguen** [comment]
Continuation of #frontend -- #44

**Comment by supakeshi** [comment]
Taylor completed backend component, will close until profile view has been set-up and add friend to the view of a non-friend profile instead.
