### ISSUE TITLE
Bug - Addressing Minor Issues with MessageView.

### ISSUE THREAD

**Issue by StefanoRubini** [UNLV-CS472-672/2024-S-GROUP3-Barbell#150]
These are the list of minor issues that have to be addressed in this issue with regards to **MessageView** in index.tsx.

<img width="905" alt="Screenshot 2024-03-28 at 5 48 30 PM" src="https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/124111831/843fd493-6b91-4b7c-9778-4d5af6f77660">

**Comment by thienguen** [comment]
Issue fall over to 8

**Comment by thienguen** [comment]
pr ready in 8
