### ISSUE TITLE
Backend -- Workout filtering

### ISSUE THREAD

**Issue by elliotwesoff** [UNLV-CS472-672/2024-S-GROUP3-Barbell#151]
#42 is the front end for this feature. This task should implement querying the back end for the desired workouts based on selections made in the front end.

**Comment by thienguen** [comment]
@AaronFmyHub this is the next issue for aaron after the workout screen structure finished in cycle 8.

Requirements:

+ add gender in user schema
+ update user.json for testing data
+ implement functionality,
+ search bar for (...more details)

**Comment by thienguen** [comment]
Fall over to cycle 9, cycle 8 aaron finished the structure issue #42 (in review)

**Comment by thienguen** [comment]
Start in cycle 10, after #224

**Comment by taylorfinelli** [comment]
Completed by @L-Hen & @taylorfinelli
