### ISSUE TITLE
Frontend -- Contact us screen

### ISSUE THREAD

**Issue by elliotwesoff** [UNLV-CS472-672/2024-S-GROUP3-Barbell#154]
Implements the "Contact Us" screen. Maybe put a cute lil google map of UNLV on there or sth idk

**Comment by thienguen** [comment]
Issue fall over to 8

**Comment by thienguen** [comment]
blocker: the bug issue, and start this

**Comment by thienguen** [comment]
fall over in cycle 9

**Comment by thienguen** [comment]
Fall over to cycle 10
