### ISSUE TITLE
Frontend -- Profile/Account screen functionality

### ISSUE THREAD

**Issue by elliotwesoff** [UNLV-CS472-672/2024-S-GROUP3-Barbell#157]
The profile/account screen structure was created. Now it needs functionality from the back end such as: 

1. Query for actual user data (get from global context?)
2. Rename profile screen to "account" screen
3. Distinguish which data will stay on account screen, which will go to (real) profile screen, and other screens
4. Implement view template for real data/integrate with back end/global context data

**Comment by thienguen** [comment]
Update:

- [ ] Toggle update to db
