### ISSUE TITLE
Frontend - Profile Screen Structure

### ISSUE THREAD

**Issue by L-Hen** [UNLV-CS472-672/2024-S-GROUP3-Barbell#163]
## Description
Set up the screen structure of the profile view.

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/123710248/1a40eeb6-1656-4ec8-a4c3-7bd2c8e7e1f4)

**Comment by thienguen** [comment]
Thank you, i will update this ticket and monitor it

**Comment by thienguen** [comment]
need user api to display on profile view

**Comment by thienguen** [comment]
Fall over 8

**Comment by thienguen** [comment]
Issue split to Taylor
Fall over to cycle 9

**Comment by L-Hen** [comment]
Closing issue, duplicated and updated
https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/issues/230

**Comment by thienguen** [comment]
I will delete the branch that associate w this
