### ISSUE TITLE
Frontend - Add testing to notifs

### ISSUE THREAD

**Issue by mva919** [UNLV-CS472-672/2024-S-GROUP3-Barbell#177]
## Description

Our notifs components and page don't have unit testing, we need to add testing to all our our components.

## Requirements

Outline the specific objectives and requirements needed to finish the issue. Clearly state what success looks like for this issue.

## (Optional)

If you have potential solutions or approaches in mind, please outline them here. This section is optional and can include any preliminary ideas or alternative strategies.

**Comment by thienguen** [comment]
ready for pr in cycle 8

**Comment by thienguen** [comment]
mark closed
