### ISSUE TITLE
Backend -- Create Profile View API

### ISSUE THREAD

**Issue by L-Hen** [UNLV-CS472-672/2024-S-GROUP3-Barbell#179]
## Description
Create an API that can get the follow user information from profile view page.
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/123710248/104e5785-0f93-4137-a6cf-237e3316d831)

**Comment by thienguen** [comment]
byId in user.ts

**Comment by thienguen** [comment]
I will close issue
