### ISSUE TITLE
Frontend -- Add functionality to Workout View

### ISSUE THREAD

**Issue by mva919** [UNLV-CS472-672/2024-S-GROUP3-Barbell#181]
## Description

Add the ability to create new sets, add exercises, rename workouts title, add timer components, check sets as completed, add unilateral sets.

![image](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/65429988/8a0cdec8-064e-4527-8dbd-e47f07af71e1)

Include any links, documents, or resources that could provide further context or information relevant to the issue.

## Requirements

Outline the specific objectives and requirements needed to finish the issue. Clearly state what success looks like for this issue.
 
Listed in description

## (Optional)

If you have potential solutions or approaches in mind, please outline them here. This section is optional and can include any preliminary ideas or alternative strategies.

**Comment by thienguen** [comment]
fall over to cycle 9, 
blocker: state management

**Comment by thienguen** [comment]
@mva919 

Discussion: split to 2
