### ISSUE TITLE
Frontend -- Workout Frequency chart

### ISSUE THREAD

**Issue by elliotwesoff** [UNLV-CS472-672/2024-S-GROUP3-Barbell#195]
## Description

Small component for displaying a bar or line chart showing the user's workout frequency over time.

## Mockup

![2024-04-09_23-01](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/7844060/2dfcb358-8e0c-4e38-887c-28f92fa1e0e2)

**Comment by BitsyBirb** [comment]
I will take a closer look into this starting later tonight. 

Might update the schema to add a field keeping track of workouts over a given month to make this more computationally feasible.

**Comment by BitsyBirb** [comment]
Updated schema and am waiting for PR #227 to be merged in to continue working. Dan and I need the new API + schema for Workout Logs.
