### ISSUE TITLE
Frontend -- Layout for notif, message feat

### ISSUE THREAD

**Issue by thienguen** [UNLV-CS472-672/2024-S-GROUP3-Barbell#20]
## Description

This is part 1 of the notification and messages feature design. Implement the navigation and layout of our social media aspect.

- Figma Design [Link](https://www.figma.com/file/XFTZsuG8ZO8mLORG8NMRBP/Barbell-Wireframe?type=design&node-id=0-1&mode=design&t=4ygVeN6AFRxlkH9n-0)
- [Dynamic routing](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes)

## Requirements

<img 
    style="display: block; 
           margin-left: auto;
           margin-right: auto;
           width: 30%;"
    src="https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/94078395/27fc1d20-326c-425c-ba1d-f4b5c382c5df" 
    alt="Our logo">
</img>

- [ ] create a new folder in app folder call inbox, in there continue to create `page.tsx`, (optional layout.tsx if we intent to go this route)
- [ ] create a component (currently blank) for each aspect (notifications, direct, group message)
- [ ] the back arrow will lead back to the default back so `/` would be the route
- [ ] within the inbox folder, create a folder name `conversation` , and dynamic routing with [id] (since we are differentiate each conversation by id, and each conversation can have 1 to many relationships w Users)
- [ ] This is a general outline, you could be creative as much as you want.

## (Optional)

Here is one of the proposes solution

- [Tutorial](https://github.com/AntonioErdeljac/next13-messenger?tab=readme-ov-file)
- [Examples code](https://github.com/AntonioErdeljac/next13-messenger?tab=readme-ov-file)

## Further Comments

See how much you can finished this, so I can wip the details of part 2 for the said issue

This will be update as we will have 2 PR separately

**Comment by taylorfinelli** [comment]
Completed with previous PRs.
