### ISSUE TITLE
Mixed -- Add gender to body diagram, dynamically resize the body

### ISSUE THREAD

**Issue by AaronFmyHub** [UNLV-CS472-672/2024-S-GROUP3-Barbell#207]
## Description

Add gender selection feature in muscle selection page and default gender to user gender.
Also resize the body to fit user machine.

## Requirements

- [x] Add gender to schema
- [x] Create a toggle that is non-indicative
- [x] Scale the Body, which is wrapped in SVG ViewBox, based on screen dimension

**Comment by thienguen** [comment]
Fall over to cycle 10
