### ISSUE TITLE
Backend -- Workoutlog router api endpoints define

### ISSUE THREAD

**Issue by thienguen** [UNLV-CS472-672/2024-S-GROUP3-Barbell#226]
## Description

We will need 4 basic API endpoints for the workout log, streak calendar, and frequency chart need this, 

## Requirements

- [x] Create one
- [x] Update one
- [x] Query all
- [x] Query by id
- [x] DO NOT WRITE DELETE WORKOUTLOG endpoint, we won't be delete anything

**Comment by BitsyBirb** [comment]
The PR should be in for this issue; I also did NOT write any such delete function...I think. Anywho, thank you for handling making this issue to let me make the endpoints; I would NOT be able to progress on my other issue without this 🙏

**Comment by BitsyBirb** [comment]
Okay so uh, Marcos has his PR in which also implements API functionality so we can just take his as well to NOT destroy his work. I recommend we review #228 instead so Dan and I can move forward.
