### ISSUE TITLE
Backend -- mock data generation, for demonstration

### ISSUE THREAD

**Issue by thienguen** [UNLV-CS472-672/2024-S-GROUP3-Barbell#231]
## Description

Now we hitting the end of the cycle. You can either use generate.py made by Elliot or manually write them through the JSON files in the mock-data folder, the entire of this issue its so we have data for demonstration

## Requirements

- [x] Have a decent amount of exercise, workout log, workout template, chat messages
- [x] users, notifications, etc.
- [ ] actual plausible data

## (Optional)

Please go to Marcos pr and grab his schema, as it is the latest schema.

**Comment by BitsyBirb** [comment]
For now I'm just going to update Elliot's old python generator. If all goes wrong, then I'll manually update data.

**Comment by BitsyBirb** [comment]
Okay I have realized generating data for everything will be rather difficult, especially things such as Spotify. As such, I can write a script to just generate demo data for a few models while we manually update the other fields.
