### ISSUE TITLE
Frontend -- New select exercise based on muscle group page

### ISSUE THREAD

**Issue by AaronFmyHub** [UNLV-CS472-672/2024-S-GROUP3-Barbell#239]
## Description

Create the page where user select exercise based on prior muscle selection.

## Requirements

- [x] Display the list of exercises we provided
- [x] Filter the list based on muscle
- [x] Have functional buttons such as reset
- [ ] Display a muscle group image for which user selected

**Comment by thienguen** [comment]
#151 Complementary
