### ISSUE TITLE
Bugs -- Making the mock data actually plausible

### ISSUE THREAD

**Issue by BitsyBirb** [UNLV-CS472-672/2024-S-GROUP3-Barbell#257]
## Description

So I previously generated a lot of mock data BUT none of it really makes sense so I'm going to quickly manually edit and make it kind of make sense. That was my bad. Sorry bout that one team. Will be updating all the data from new-gen-data and moving it to clean-gen-data.

Include any links, documents, or resources that could provide further context or information relevant to the issue.

- [Link](#)

## Requirements

Outline the specific objectives and requirements needed to finish the issue. Clearly state what success looks like for this issue.

- [ ] Clean up/make data from new-gen-data plausible.
- [ ] Move over to new folder to keep things organized
- [ ] Update seed.tsx to work with new paths.
- [ ] Test seed.tsx on my DB instance.

## (Optional)

If you have potential solutions or approaches in mind, please outline them here. This section is optional and can include any preliminary ideas or alternative strategies.

Later on I could make files that help generate pseudo-natural data but that is a major stretch goal as natural language is a bit difficult to generate.

**Comment by thienguen** [comment]
as a person who merged the pr I think is also part of my bad, I did minimum seeding ability, but didn't go through the studio to verify those data. 

So this issue having the highest priority as of rn

**Comment by BitsyBirb** [comment]
Yup I am on it immediately. I will have this in by 5PM at the latest.
