### ISSUE TITLE
Frontend - Start New Work Screen Sctructure

### ISSUE THREAD

**Issue by mva919** [UNLV-CS472-672/2024-S-GROUP3-Barbell#35]

**Comment by elliotwesoff** [comment]
Hey @mva919 you mentioned in the meeting today that you were going to work on the workout tracker next. Is this the issue for that, or did #64 duplicate this task, or is this something else?

**Comment by L-Hen** [comment]
Is this the same one as https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/issues/39 ?

**Comment by mva919** [comment]
Yea let me delete this issue
