### ISSUE TITLE
Frontend - Filter by equipment Screen Structure

### ISSUE THREAD

**Issue by taylorfinelli** [UNLV-CS472-672/2024-S-GROUP3-Barbell#40]
![Screenshot 2024-03-05 at 4 32 09 PM](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/85365584/5c213184-dbb9-4f75-8da0-2feaadcfd88f)

**Comment by thienguen** [comment]
@L-Hen
