### ISSUE TITLE
Frontend -- Create an avatar component

### ISSUE THREAD

**Issue by supakeshi** [UNLV-CS472-672/2024-S-GROUP3-Barbell#95]
![friendslist](https://github.com/UNLV-CS472-672/2024-S-GROUP3-Barbell/assets/64014075/1cac5937-2559-4f28-9b85-3ad7497f013c)
(Example of an avatar component in use)

Create a component that will generate the referenced user's avatar that will:

pass the image the user has chosen to be their avatar when used, or generate the user's initials should an image be unavailable.

**Comment by thienguen** [comment]
discussion: stretch goal

**Comment by thienguen** [comment]
note: If I get chat real time feature to works + spotify, I can nextly setup a bucket for avatar component. Closed for now
